version: '3.7'

services:

  db:
    image: veronezi/sample-postgres
    ports:
      - "5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
    healthcheck:
      test: ["CMD", "bash", "/opt/create_base_backup.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 2s
    volumes:
      - type: bind
        source: ${TMP}/volumes/backup
        target: /opt/backup
      - type: bind
        source: ${TMP}/volumes/db_data
        target: /var/lib/postgresql
