version: '3.7'

services:

  db:
    image: veronezi/sample-postgres
    ports:
      - "5432"
    environment:
      - RESTORE_BASE_BACKUP=base.tar
      - DEBUG=false
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
    volumes:
      - type: bind
        source: ${TMP}/volumes/backup
        target: /opt/backup
      - type: bind
        source: ${TMP}/volumes/db_data
        target: /var/lib/postgresql
